# ...existing code...
name: on-push-main
on:
  push:
    branches:
      - main

jobs:
  install-nodeJS:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "24.11.0"

      - name: Install dependencies
        run: npm ci

      - name: Execute linting
        run: npm run lint

      - name: Run app
        run: npm start

      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: project-artifact
# ...existing code...
